### ISSUE TITLE
Connecting multiple accounts - show a new login page for each new connection

### ISSUE THREAD

**Issue by fistuk** [dropbox/dropbox-sdk-java#236] opened 2019-02-21 11:52 UTC
Hi, I have an android app, and I want to connect multiple Dropbox accounts. When connecting the first one, I see the following screen:

![screen shot 2019-02-21 at 13 40 07](https://user-images.githubusercontent.com/1989685/53167142-cc1de080-35df-11e9-9813-afb6a3f91320.png)

After successful authentication, I'm storing the user's access token and now trying to connect another user. When launching an authentication flow for the second user, I see the following screen:

![screen shot 2019-02-21 at 13 43 34](https://user-images.githubusercontent.com/1989685/53167150-d2ac5800-35df-11e9-9413-eef49c0ddabc.png)

To connect a secondary account, the user must firstly click sign out to return to the login page and only then login in with the new credentials. 
The question is whether it's possible to show an initial login page for each newly initiated auth flow without the need to click sign out.

**Comment by greg-db** [comment] 2019-02-21 16:49
No, unfortunately the Java SDK doesn't offer a way to automatically log out the user currently signed in to www.dropbox.com for the authorization flow like this, but I'll pass this along as a feature request.

**Comment by handstandsam** [comment] 2022-09-23 13:20
This is expected behavior.

Rationale: We want to leverage the account currently logged into the system browser (as that's what the user would typically use, and possibly already be authenticated in).  By doing this we are making the authentication process much simpler to use because the friction of remembering an entering a username and password is not required.

In your case, it should still work if the user logs out and logs back in as the new user.  This is not ideal, but at this point, this is an edge use case.

@greg-db - If we can identify this as a feature of many developers, we could consider looking into this feature request.

Closing the issue because this is expected behavior.

**Closed by handstandsam** 2022-09-23 13:20 UTC
Labels: enhancement
