### ISSUE TITLE
ServerException unexpectedStatus on file upload (Android)

### ISSUE THREAD

**Issue by ISCHI** [dropbox/dropbox-sdk-java#165] opened 2017-11-06 18:43 UTC
I use the dropbox SDK (com.dropbox.core:dropbox-core-sdk:3.0.5) to upload a file (mode: overwrite) to dropbox. It works fine on my Android devices and the emulator. A customer reported an issue with the upload function. He uses a SAMSUNG Galaxy S3 (Android 4.3). I have some logged exception details: the dropbox SDK throws an server exception without message:

```
Non-fatal Exception: com.dropbox.core.ServerException
       at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:344)
       at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:285)
       at com.dropbox.core.DbxUploader.finish(DbxUploader.java:228)
       at com.dropbox.core.DbxUploader.uploadAndFinish(DbxUploader.java:106)
       at com.dropbox.core.v2.DbxUploadStyleBuilder.uploadAndFinish(DbxUploadStyleBuilder.java:92)
       at ...
```

I don't know if the problem is caused by the account or the device.

The upload implementation is very simple and works for other accounts/devices:
```
File file = new File(path);
FileInputStream inputStream = new FileInputStream(file);
mDbxClient.files().uploadBuilder("/filename")
     .withMode(WriteMode.OVERWRITE)
     .uploadAndFinish(inputStream);
```

Is this a known bug?

**Comment by greg-db** [comment] 2017-11-06 19:15
Thanks for the report! Please share the request ID so we can look into it. You can get it using [`DbxException.getRequestId`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/DbxException.html#getRequestId--).

**Comment by ISCHI** [comment] 2017-11-07 13:59
I have 4 request IDs for the issue:

- db6c440417eefd69de033ee4168eee9b
- 25883b05fca981513eddb4f1aec9d9f3
- 31288182463eb87b9a3cb3d6ab7e857c
- 0b0fbdc2847552e61c0159d3caec6f4a

**Comment by greg-db** [comment] 2017-11-07 14:47
Thanks! That's helpful. It looks like this is actually related to how the User-Agent is being handled. Can you share the code where you build your `DbxRequestConfig`, including your `clientIdentifier`? Thanks in advance!

**Comment by ISCHI** [comment] 2017-11-07 15:43
That was a good hint. I use umlauts (äöü) within the client identifier.
I have built a new version without umlauts and will provide it for testing. I'll contact you with the result.

**Comment by greg-db** [comment] 2017-11-07 15:50
Yes, eliminating those characters should avoid the issue. 

If possible, please still share the code though so we can reproduce exactly what you had so we can look into handling this case better. Thanks!

**Comment by ISCHI** [comment] 2017-11-07 15:58
I can't tell you the concrete name of the app, but I can share the code:

```
// This is not the real app client name, but should produce the issue
final static private String APP_CLIENT_NAME = "Test für Umlaut Fehler äüö";

private void initializeDbxClient() {
   DbxRequestConfig requestConfig = DbxRequestConfig.newBuilder(APP_CLIENT_NAME).build();
   mDbxClient = new DbxClientV2(requestConfig, accessToken);
   ...
}
```

**Comment by greg-db** [comment] 2017-11-07 17:29
Thank you!

**Comment by ISCHI** [comment] 2017-11-09 12:23
The test confirmed the assumption. The server exception occurs only with umlauts in the client name. The problem is solved (for me) by the "remove all umlauts workaround".

**Comment by greg-db** [comment] 2017-12-08 16:37
This should be fixed on our side now as well, so you should be able the original user agent string.

**Closed by greg-db** 2017-12-08 16:37 UTC
