### ISSUE TITLE
Retrieved Image contains no metadata for PNG files

### ISSUE THREAD

**Issue by phileo** [dropbox/dropbox-sdk-java#73] opened 2016-10-12 00:48 UTC
# I am making a request for image files with metadata as follows:

`dbxClient.files()
               .listFolderBuilder(path)
               .withIncludeMediaInfo(true)
               .start();`

However, in the response that comes back, `FileMetadata.getMediaInfo() = null` for half of my images.
Any reason why this is happening, or what am I doing wrong?

**Comment by zjiuyang** [comment] 2016-10-12 01:23
Hi @phileo , may you please provide more information about the image? What's the format of images missing MediaInfo? Also our server generates mediaInfo in async so there might be a delay between your image getting upload and listFolder/getMetadata being able to retrieve their mediaInfo.

**Comment by phileo** [comment] 2016-10-12 01:57
The images that are failing are PNG's.
if the server is generating mediaInfo in async, then how do I retrieve mediaInfo? 
I am already calling `dbxClient.files() .listFolderBuilder(path) .withIncludeMediaInfo(true) .start();` in a separate thread and waiting for the result

**Comment by zjiuyang** [comment] 2016-10-12 08:20
Hi @phileo, I just reproduced and confirmed that server side won't generate MediaInfo for PNG.

Never mind about the async stuff. Because even if the media info is not generated yet, `FileMetadata.getMediaInfo()` should still return a `MediaInfo` tagged pending instead of null.

**Comment by phileo** [comment] 2016-10-12 14:23
http://www.libpng.org/pub/png/spec/1.2/png-1.2.pdf
Can the server just read the IHDR chunk of the PNG header and at least  return a valid MediaInfo.Dimensions ?

**Comment by greg-db** [comment] 2016-10-12 18:16
We can't make any promises, but we'll consider this a feature request for media metadata for PNG files.

**Comment by handstandsam** [comment] 2022-09-23 12:33
Thanks @greg-db for relaying this information to our server team.  I'm going to close this on the Java SDK project here.

**Closed by handstandsam** 2022-09-23 12:33 UTC
Labels: enhancement
