### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Aiuspaktyn** [dropbox/dropbox-sdk-java#148] opened 2017-09-25 09:42 UTC
```
Fatal Exception: java.lang.NullPointerException: src == null
       at java.lang.System.arraycopy(System.java)
       at java.io.PipedInputStream.read(PipedInputStream.java:344)
       at okio.Okio$2.read(Unknown Source)
       at okio.RealBufferedSink.writeAll(Unknown Source)
       at com.dropbox.core.http.OkHttpUtil$PipedStream.writeTo(Unknown Source)
       at com.dropbox.core.http.OkHttp3Requestor$PipedRequestBody.writeTo(Unknown Source)
       at okhttp3.internal.http.CallServerInterceptor.intercept(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.cancel(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.RealCall.getResponseWithInterceptorChain(Unknown Source)
       at okhttp3.RealCall$AsyncCall.execute(Unknown Source)
       at okhttp3.internal.NamedRunnable.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)
```

**Comment by greg-db** [comment] 2017-09-25 15:44
Thanks for the post! We'll be happy to look into this, but we'll need some more information. Please reply with:
- the steps to reproduce the issue
- the relevant code
- the version of Java/Android that you're see this with
- the version of the Dropbox Java SDK you're using

Thanks in advance!

**Comment by Aiuspaktyn** [comment] 2017-09-26 07:33
Hi, I can't reproduce, it's a Crashlytics report:

[com.aiuspaktyn.spyrecorderpro_issue_23_crash_59C35A4F03A100011C7C4226FC667E1C_abe1c6749fd511e7a63f56847afe9799_0_v2.txt](https://github.com/dropbox/dropbox-sdk-java/files/1332159/com.aiuspaktyn.spyrecorderpro_issue_23_crash_59C35A4F03A100011C7C4226FC667E1C_abe1c6749fd511e7a63f56847afe9799_0_v2.txt)

Thanks!

**Comment by greg-db** [comment] 2017-09-26 19:13
Thanks! I believe this one is a duplicate of #107. In short, this appears to be a bug in older versions of Java, so it should already be fixed in Android SDK 24. The report does list OS version 4.4.2, which is SDK 19.

**Closed by greg-db** 2017-09-26 19:13 UTC
