### ISSUE TITLE
Large length file name string causes StackOverFlow error when upload a file

### ISSUE THREAD

**Issue by shuson** [dropbox/dropbox-sdk-java#150] opened 2017-09-28 02:08 UTC
Hi genius, I am using SDK version 3.0.4 to upload a file with name length 10001 characters.

Class CommitInfo, line 176. `Pattern.matches("(/(.|[\\r\\n])*)|(ns:[0-9]+(/.*)?)|(id:.*)", path)`. 
The repetitive alternative regular expression will make Java's builtin regex engine compiled into a recursive call, which results `java.lang.StackOverflowError`

Any advice on it?
Thanks in advance.

**Comment by greg-db** [comment] 2017-09-28 02:23
Thanks for the report! We'll look into it.

**Comment by greg-db** [comment] 2017-10-04 16:20
The team looked into this, and unfortunately we're not going to be able to offer a solution. 

Given the lack of OS support (e.g., [Windows only supports up to 260 characters](https://msdn.microsoft.com/en-us/library/aa365247(v=vs.85).aspx)), and that the cause is a combination of the regex our API happens to use, plus [the issue with this kind of regex in Java itself](https://stackoverflow.com/a/7510006), we are marking this as won't fix. We recommend updating your app to avoid very long paths like this. Apologies I don't have better news for you!

**Closed by greg-db** 2017-10-04 16:20 UTC
Labels: wontfix

**Comment by shuson** [comment] 2017-10-08 09:53
No problem, thanks for your advice.
