### ISSUE TITLE
Error loading version from resource "sdk-version.txt": Not found

### ISSUE THREAD

**Issue by chrisonline** [dropbox/dropbox-sdk-java#187] opened 2018-04-16 18:18 UTC
In my Crashlytics log I get some RuntimeException:

```
Caused by java.lang.RuntimeException
Error loading version from resource "sdk-version.txt": Not found.
com.dropbox.core.DbxSdkVersion.loadVersion

com.dropbox.core.DbxSdkVersion.loadVersion (DbxSdkVersion.java:66)
com.dropbox.core.DbxSdkVersion. (DbxSdkVersion.java:17)
com.dropbox.core.DbxRequestUtil.buildUserAgentHeader (DbxRequestUtil.java:1151)
com.dropbox.core.DbxRequestUtil.startPostRaw (DbxRequestUtil.java:233)
com.dropbox.core.v2.DbxRawClientV2$1.execute (DbxRawClientV2.java:107)
com.dropbox.core.v2.DbxRawClientV2.addAuthHeaders (DbxRawClientV2.java:284)
com.dropbox.core.v2.DbxRawClientV2.addAuthHeaders (DbxRawClientV2.java:102)
com.dropbox.core.v2.users.DbxUserUsersRequests.getCurrentAccount (DbxUserUsersRequests.java:120)
com.colapps.reminder.cloud.DropBoxGetCurrentAccountTask.doInBackground$2ca27cfb (Unknown Source)
com.colapps.reminder.cloud.DropBoxGetCurrentAccountTask.doInBackground (Unknown Source)
android.os.AsyncTask$2.call (AsyncTask.java)
```

I am using version 3.0.5 with ProGuard.

**Comment by greg-db** [comment] 2018-04-16 18:28
This looks like a duplicate of #140 , so I'm closing this in favor of that one. Please review the information there regarding this issue.

**Closed by greg-db** 2018-04-16 18:28 UTC
