### ISSUE TITLE
Crash after aborting file upload

### ISSUE THREAD

**Issue by steosoft** [dropbox/dropbox-sdk-java#107] opened 2017-04-23 22:52 UTC
App crashes after aborting file upload to dropbox, not always but when upload is in 'final' stage (e.g. upload usually takes 30 seconds and I abort it in 25 sec).
I'm using version 3.0.2.

Here's the relevant part of my code:
```
private UploadUploader uploadUploader;

public boolean uploadFile(String filepath, String filename) {
    InputStream inputStream;
    try {
        inputStream = new FileInputStream(filepath);
        uploadUploader = mDbxClient.files().uploadBuilder(filename).withMode(WriteMode.OVERWRITE).start();
        uploadUploader.uploadAndFinish(inputStream);
        return true;
    } catch(DbxException | IOException e) {
        e.printStackTrace();
    }
    return false;
}

public void cancelUpload() {
    if(uploadUploader != null) 
        uploadUploader.abort();
}
```

And here's the exception:

```
FATAL EXCEPTION: OkHttp Dispatcher
Process: pl.xxx.yyy, PID: 8329
java.lang.NullPointerException: src == null
    at java.lang.System.arraycopy(System.java:275)
    at java.io.PipedInputStream.read(PipedInputStream.java:344)
    at okio.Okio$2.read(Okio.java:138)
    at okio.RealBufferedSink.writeAll(RealBufferedSink.java:97)
    at com.dropbox.core.http.OkHttpUtil$PipedStream.writeTo(OkHttpUtil.java:79)
    at com.dropbox.core.http.OkHttp3Requestor$PipedRequestBody.writeTo(OkHttp3Requestor.java:355)
    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:48)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by greg-db** [comment] 2017-04-24 22:14
Thanks for the report @steosoft . I can't seem to reproduce this issue, so some more information would be helpful. Can you share:
- the code you're using to construct your `mDbxClient`.
- what version of okhttp you have installed.
- about what percent of aborted uploads throw this exception.

Thanks in advance!

**Comment by steosoft** [comment] 2017-04-25 08:01
Thanks for your answer.

Here's my initialization code (taken from samples):
```
public class DropboxClientFactory {

    private static DbxClientV2 sDbxClient;

    public static void init(String accessToken) {
        if (sDbxClient == null) {
            DbxRequestConfig requestConfig = DbxRequestConfig.newBuilder("my-app")
                .withHttpRequestor(new OkHttp3Requestor(OkHttp3Requestor.defaultOkHttpClient()))
                .build();

            sDbxClient = new DbxClientV2(requestConfig, accessToken);
        }
    }

    public static DbxClientV2 getClient() {
        if (sDbxClient == null) {
            throw new IllegalStateException("Client not initialized.");
        }
        return sDbxClient;
    }
}
```

okhttp version:
```
    compile 'com.squareup.okhttp:okhttp:2.7.5'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
```

As I said crash happens everytime but only if upload is finishing (e.g. upload takes around 30 seconds and I abort it after let's say 25 seconds), if I abort it earlier it doesn't crash.

Also it's weird that upload takes a lot of time - file is max 1MB and it's uploading 30 seconds or more. After few seconds it's already visible in my dropbox account (on website) but method uploadAndFinish ends after 30 seconds or more. What's the issue?

I found some solution to abort file upload without crash but I don't know is it completely safe?
I changed my initialization class to:
```
public class DropboxClientFactory {

    private static DbxClientV2 sDbxClient;
    private static OkHttpClient okHttpClient;

    public static void init(String accessToken) {
        if (sDbxClient == null) {
            okHttpClient = OkHttp3Requestor.defaultOkHttpClient();
            DbxRequestConfig requestConfig = DbxRequestConfig.newBuilder("my-app")
                .withHttpRequestor(new OkHttp3Requestor(okHttpClient))
                .build();

            sDbxClient = new DbxClientV2(requestConfig, accessToken);
        }
    }

    public static DbxClientV2 getClient() {
        if (sDbxClient == null) {
            throw new IllegalStateException("Client not initialized.");
        }
        return sDbxClient;
    }

    public static OkHttpClient getOkHttpClient() {
        return okHttpClient;
    }
}
```

and when I want to abort upload I'm not calling
`uploadUploader.abort();`
but
`DropboxClientFactory.getOkHttpClient().dispatcher().cancelAll();`

**Comment by greg-db** [comment] 2017-04-26 22:23
Thanks! We'll look into it.

**Comment by satishshenoy** [comment] 2017-05-22 04:58
Any updates regarding this issue? 
Same issue am facing. as told by steosoft am also getting same error. crash is happening 7/10 times.

**Comment by jiuyangzhao** [comment] 2017-05-22 09:52
I just read through PipedInputStream code in Java 1.8 there is no way read(..) can throw NPE. I think you definitely hit a bug in old version of java.

Which version of Java are you using?

Also `DropboxClientFactory.getOkHttpClient().dispatcher().cancelAll();` is just a for loop calling cancel to all the ongoing requests. (while in abort() we just call cancel to that specific upload request) I can't see how this can avoid NPE and obviously it's not safe unless your app only make one request to Dropbox at a time.

**Comment by steosoft** [comment] 2017-05-25 12:33
@jiuyangzhao Android by default is using Java 1.7, is there a bug in old version which could cause that behaviour?
I used `DropboxClientFactory.getOkHttpClient().dispatcher().cancelAll();` in application and testers didn't report any crash. Application is making only one request to Dropbox at a time.

**Comment by jiuyangzhao** [comment] 2017-05-31 02:45
@steosoft I just took a look at android source code. This bug was fixed in Android SDK 24. The root cause is there is some race condition if we close the `PipedInputStream` when `read` is still waiting.

Your work around doesn't crash because you don't close the pipedInputStream we used in RequestBody. So there will be a thread keep copying input stream to the real sink even after you abort the request. If we don't care about this then it's fine.

BTW I hope you are aware of that abort is not 100% guaranteed. Sometimes you can still see you uploaded a file to Dropbox after you abort the request from SDK.

**Comment by steosoft** [comment] 2017-06-01 07:27
@jiuyangzhao thanks for your answer. So on devices with Android >= 7.0 (API 24) abort should work without crashing?
In my application it's not the issue if abort is not 100% guaranteed and file will be uploaded anyway.

**Comment by jiuyangzhao** [comment] 2017-06-05 22:12
@steosoft  Yes at lease devices >= 24 won't throw NPE. Because the close function in 24 was rewrote (copied from standard JAVA 7) and there won't be code like `buffer = null`

**Closed by jiuyangzhao** 2017-06-05 22:12 UTC
