### ISSUE TITLE
AuthActivity not found when Dropbox app installed with Android target SDK 33 on Android 13 device

### ISSUE THREAD

**Issue by michaelkircher** [dropbox/dropbox-sdk-java#466] opened 2022-10-02 19:35 UTC
Setup: Android app using latest Dropbox SDK 5.4.1, but also with 5.1.1. Android target SDK 33. Testing on device with Android 13. 

When authenticating while having the Dropbox app installed on the device the activity is not found: 
android.content.ActivityNotFoundException: Unable to find explicit activity class
{my.app.domain/com.dropbox.core.android.AuthActivity}.

Trying the same without the Dropbox app installed and using the browser works.
Trying the same with the Dropbox app installed on a Android 9 device works.

Changing to Android target SDK 32 as single change, will make authentication again work with the Dropbox app installed on also on Android 13 device.

**Comment by devPalacio** [comment] 2022-10-03 12:34
Hey @michaelkircher, could you try the following?
- https://github.com/dropbox/dropbox-sdk-java/issues/406#issuecomment-1215155110
- This issue goes into the background of why it's needed: https://github.com/dropbox/dropbox-sdk-java/issues/461

**Comment by devPalacio** [comment] 2022-10-03 13:03
Also, could you let me know what version of the Dropbox App you have installed?

You can find it by navigating to the settings page and scrolling down to `App version` in the Dropbox app.

**Comment by michaelkircher** [comment] 2022-10-03 13:50
> Also, could you let me know what version of the Dropbox App you have installed?
> You can find it by navigating to the settings page and scrolling down to `App version` in the Dropbox app.

298.2.2 - so it seems it is still problematic

Entering a second intent-filter entry in the Manifest does the trick, but I guess it can lead to other side effects, when multiple apps expecting Dropbox handshakes are installed on the end user's device?

**Comment by devPalacio** [comment] 2022-10-03 14:07
Thank you for verifying. It's not the ideal workaround, we'll look into further changes in the Dropbox app that will eliminate the need for the generic intent filter.

**Comment by handstandsam** [comment] 2022-10-06 21:10
Duplicate of #406

**Closed by handstandsam** 2022-10-06 21:10 UTC
Labels: duplicate
