### ISSUE TITLE
how to get the file downloading/uploading progres

### ISSUE THREAD

**Issue by kbboss** [dropbox/dropbox-sdk-java#189] opened 2018-05-10 01:29 UTC
for a long time, how to get the file downloading/uploading progress

**Comment by greg-db** [comment] 2018-05-10 11:57
The API v2 Java SDK doesn't offer download/upload progress listeners, but this is open as a feature request. This is a duplicate of #66.

**Closed by greg-db** 2018-05-10 11:57 UTC
Labels: duplicate, enhancement

**Comment by kbboss** [comment] 2018-08-24 03:11
@greg-db  how about now . Does sdk support it?

**Comment by greg-db** [comment] 2018-08-24 13:35
This is planned for the next release. Please refer to #66 for more information.
