### ISSUE TITLE
Latest Dropbox SDK not working?

### ISSUE THREAD

**Issue by guidedways** [dropbox/dropbox-sdk-java#221] opened 2018-11-28 20:37 UTC
Consistently getting these stack traces from a lot of people:

```
The following error was received during sync: 
com.dropbox.core.DbxSdkVersion, Stack: java.lang.NoClassDefFoundError: 
com.dropbox.core.DbxSdkVersion 
at com.dropbox.core.DbxRequestUtil.buildUserAgentHeader(SourceFile:160) 
at com.dropbox.core.DbxRequestUtil.addUserAgentHeader(SourceFile:145) 
at com.dropbox.core.DbxRequestUtil.startPostRaw(SourceFile:252) 
at com.dropbox.core.v2.DbxRawClientV2$1.execute(SourceFile:121) 
at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(SourceFile:306) 
at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(SourceFile:116) 
at com.dropbox.core.v2.files.DbxUserFilesRequests.search(SourceFile:2908) 
at com.dropbox.core.v2.files.SearchBuilder.start(SourceFile:98) 
at 
com.ourapp.sync.dropbox.WebDAVConnect.WebDAVConnectDropbox.b(SourceFile:305) 
at 
com.ourapp.sync.dropbox.DropboxSyncHelper.b(SourceFile:1201) 
at 
com.ourapp.sync.dropbox.DropboxSyncHelper.a(SourceFile:295) 
at com.ourapp.services.TaskSyncService.a(SourceFile:239) 
at 
com.ourapp.services.TaskSyncService.lambda$7TloCRM13zuPYo8Pwm3I9w0JIHA(Unknown 
Source:0) 
at 
com.ourapp.services.-$$Lambda$TaskSyncService$7TloCRM13zuPYo8Pwm3I9w0JIHA.run(Unknown 
Source:8) 
at java.lang.Thread.run(Thread.java:764) 
Caused by: java.lang.ExceptionInInitializerError 
... 15 more 
Caused by: java.lang.RuntimeException: Error loading version from resource 
"sdk-version.txt": Not found. 
at com.dropbox.core.DbxSdkVersion.loadVersion(SourceFile:66) 
at com.dropbox.core.DbxSdkVersion.<clinit>(SourceFile:17) 
... 15 more
```

**Comment by greg-db** [comment] 2018-11-28 21:14
This looks like a duplicate of #140 , so I'm closing this in favor of that one. Please review the information there regarding this issue.

**Closed by greg-db** 2018-11-28 21:14 UTC
